
$opaque
$modelname	jessev92/cobra/weapons/C49AR_w
$model	C49AR	weapons/C49AR_w
$cdmaterials	models/jessev92/cobra/Weapons
$cdmaterials	models/jessev92/cobra/Weapons/c49ar
$cdmaterials	models/jessev92/cobra/Weapons/common
$attachment "muzzle"	"muzzle" 	0 0 0 rotate 0 0 0
$attachment "1"			"eject" 	0 0 0 rotate 0 0 0
$surfaceprop	weapon
$contents		solid
$sequence	idle	weapons/C49AR_w {	fps 1	}
$collisionmodel weapons/C49AR_w
{
	$mass 20
	$inertia 1
	$damping 0
	$rotdamping 0

}

