
$opaque
$modelname	jessev92/cobra/weapons/C65sp_w
$model	C65SP	weapons/C65sp_w
$cdmaterials	models/jessev92/cobra/Weapons
$cdmaterials	models/jessev92/cobra/Weapons/C65SP
$cdmaterials	models/jessev92/cobra/Weapons/common
$attachment "muzzle"	"muzzle" 	0 0 0 rotate 0 0 0
$attachment "1"			"eject" 	0 0 0 rotate 0 0 0
$surfaceprop	weapon
$contents		solid
$sequence	idle	weapons/C65sp_w {	fps 1	}
$collisionmodel weapons/C65sp_w
{
	$mass 20
	$inertia 1
	$damping 0
	$rotdamping 0

}

