
$opaque
$modelname	jessev92/cobra/weapons/C98S1_w
$model	C98S1	weapons/C98S1_w
$cdmaterials	models/jessev92/cobra/Weapons
$cdmaterials	models/jessev92/cobra/Weapons/C98S1
$cdmaterials	models/jessev92/cobra/Weapons/common
$attachment "muzzle"	"muzzle" 	0 0 0 rotate 0 0 0
$attachment "1"			"eject" 	0 0 0 rotate 0 0 0
$surfaceprop	weapon
$contents		solid
$sequence	idle	weapons/C98S1_w {	fps 1	}
$collisionmodel weapons/C98S1_w
{
	$mass 20
	$inertia 1
	$damping 0
	$rotdamping 0

}

