
$opaque
$modelname	jessev92/cobra/weapons/cobrapistol_w
$model	CobraPistol	weapons/cobrapistol_w
$cdmaterials	models/jessev92/cobra/Weapons
$cdmaterials	models/jessev92/cobra/Weapons/cobrapistol
$cdmaterials	models/jessev92/cobra/Weapons/common
$attachment "muzzle"	"muzzle" 	0 0 0 rotate 0 0 0
$surfaceprop	weapon
$contents		solid
$sequence	idle	weapons/cobrapistol_w {	fps 1	}
$collisionmodel weapons/cobrapistol_w
{
	$mass 20
	$inertia 1
	$damping 0
	$rotdamping 0

}

