
$opaque
$modelname	jessev92/gijoe/weapons/j24ar_w
$model	J24AR	weapons/j24ar_w
$cdmaterials	models/jessev92/gijoe/Weapons
$cdmaterials	models/jessev92/gijoe/Weapons/j24ar
$cdmaterials	models/jessev92/gijoe/Weapons/common
$attachment "muzzle"	"muzzle" 	0 0 0 rotate 0 0 0
$surfaceprop	weapon
$contents		solid
$sequence	idle	weapons/j24ar_w {	fps 1	}
$collisionmodel weapons/j24ar_w
{
	$mass 20
	$inertia 1
	$damping 0
	$rotdamping 0

}

