
$opaque
$modelname	jessev92/gijoe/weapons/J3A1SG_w
$model	J3A1SG	weapons/J3A1SG_w
$cdmaterials	models/jessev92/gijoe/Weapons
$cdmaterials	models/jessev92/gijoe/Weapons/J3A1SG
$cdmaterials	models/jessev92/gijoe/Weapons/common
$attachment "muzzle"	"muzzle" 	0 0 0 rotate 0 0 0
$surfaceprop	weapon
$contents		solid
$sequence	idle	weapons/J3A1SG_w {	fps 1	}
$collisionmodel weapons/J3A1SG_w
{
	$mass 20
	$inertia 1
	$damping 0
	$rotdamping 0

}

