
$opaque
$modelname	jessev92/gijoe/weapons/J4SR3_w
$model	J4SR3	weapons/J4SR3_w
$cdmaterials	models/jessev92/gijoe/Weapons
$cdmaterials	models/jessev92/gijoe/Weapons/J4SR3
$cdmaterials	models/jessev92/gijoe/Weapons/common
$attachment "muzzle"	"muzzle" 	0 0 0 rotate 0 0 0
$surfaceprop	weapon
$contents		solid
$sequence	idle	weapons/J4SR3_w {	fps 1	}
$collisionmodel weapons/J4SR3_w
{
	$mass 20
	$inertia 1
	$damping 0
	$rotdamping 0

}

