
$opaque
$modelname	jessev92/gijoe/weapons/J67SP_w
$model	J67SP	weapons/J67SP_w
$cdmaterials	models/jessev92/gijoe/Weapons
$cdmaterials	models/jessev92/gijoe/Weapons/J67SP
$cdmaterials	models/jessev92/gijoe/Weapons/common
$attachment "muzzle"	"muzzle" 	0 0 0 rotate 0 0 0
$surfaceprop	weapon
$contents		solid
$sequence	idle	weapons/J67SP_w {	fps 1	}
$collisionmodel weapons/J67SP_w
{
	$mass 20
	$inertia 1
	$damping 0
	$rotdamping 0

}

