
$opaque
$modelname	jessev92/gijoe/weapons/joerifle_w
$model	JoeRifle	weapons/joerifle_w
$cdmaterials	models/jessev92/gijoe/Weapons
$cdmaterials	models/jessev92/gijoe/Weapons/joerifle
$cdmaterials	models/jessev92/gijoe/Weapons/common
$attachment "muzzle"	"muzzle" 	0 0 0 rotate 0 0 0
$surfaceprop	weapon
$contents		solid
$sequence	idle	weapons/joerifle_w {	fps 1	}
$collisionmodel weapons/joerifle_w
{
	$mass 20
	$inertia 1
	$damping 0
	$rotdamping 0

}

